# Generated by Django 6.0.2 on 2026-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantserver', '0003_emails_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='public_key',
            field=models.TextField(),
        ),
    ]
